### ISSUE TITLE
I have a question about iq.-data-cache-parser

### ISSUE THREAD

**Issue by chali26** [zackmark29/hlsdl-2021#1]
[
![image](https://user-images.githubusercontent.com/73935991/134895084-78958bea-2205-41c3-850f-0c265effe8eb.png)
![image](https://user-images.githubusercontent.com/73935991/134895122-f5f9dbbb-4a14-4bbd-b9b6-01e1cfa0d3c0.png)
](url)
Because I saw that it was your project, but I didn't find the specific post, SO I want to ask you in this post .where is IQIY Paser tool in the picture below, because I got 
https://cache-video.iq.com/dash tvid=7445402587137500&bid=600&vid=abe2c4788688b54418ebe6a4119bf1a5&src=01011021010010000000&vt=0&rs=1&uid=0&ori=pcw&ps=0&k_uid=800e049e9c15fae93d416a41a98ff930&pt=0&d=0&s=&lid=&slid=1&cf=&ct=&authKey=6f824bbc3fa98506654a384dc4285d95&k_tag=1&ost=0&ppt=0&dfp=a1eb0a853672ce57d2b2e5f43d33201ab0168b98f29b7475c7d00347f3e23f9c0f&prio=%7B%22ff%22%3A%22f4v%22%2C%22code%22%3A2%7D&k_err_retries=0&up=&su=1&applang=en_us&sver=2&qd_v=2&tm=1632739486951&qdy=a&qds=0&k_ft1=141287244169348&k_ft4=8196&k_ft5=1&bop=%7B%22version%22%3A%2210.0%22%2C%22dfp%22%3A%22a1eb0a853672ce57d2b2e5f43d33201ab0168b98f29b7475c7d00347f3e23f9c0f%22%7D&ut=0&vf=d7833c472094e2553634eef903f888a3
 but I don't know how to parse the link to MP4. If you see it, please help to reply to me. Thank you

**Comment by zackmark29** [comment]
Hi yeah it was deleted long time ago. 
I just forgot to remove that note with Parser tool. That's my very old tool
don't mind it. You can just paste that cache data in your browser and then copy and paste the json data here
http://www.bejson.com/jsonviewernew/
and find the m3u8 data then paste to notepad and save as file.m3u8

Then you can now download the m3u8 using  m3u8 downloader like https://github.com/nilaoda/N_m3u8DL-CLI

looks like your just getting 720p, you should set first the resolution from the player before clicking the script
